name: Runners hospedados - Docker

on: 
  workflow_dispatch:

jobs:
  docker:
    name: Contenerizacion con Podman y .NET
    runs-on: [self-hosted, windows]
    steps:
    - uses: actions/checkout@v4
    - name: docker build
      run: podman build src/wpm-api --file src/wpm-api/WisdomPetMedicine.Api/Dockerfile --tag github-action-esencial
